### ISSUE TITLE
Åland Islands is missing

### ISSUE THREAD

**Issue by nilseriksson** [onomojo/i18n_country_select#20]
Is there a reason why the countries that are included in the select is not in sync with the countries available in the i18n_country_select gem? The one I need included is AX, Åland Islands.

`I18n.backend.send(:translations)[:en][:countries].keys.map(&:to_s) - I18nCountrySelect::Countries::COUNTRY_CODES`

**Comment by sophiedeziel** [comment]
PR #19 seems to fix it
